version: 2

project_name: xodo

builds:
  - env:
      - CGO_ENABLED=1  # needed for go-sqlite3
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: xodo
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-musl
          - CXX=zig c++ -target aarch64-linux-musl

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
