version: 2

project_name: xodo

builds:
  - env:
      - CGO_ENABLED=1  # needed for go-sqlite3
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: xodo

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
